PROFILE = {
    "name": "Max Menezes",
    "email": "maxdiasmenezes@gmail.com",
    "linkedin": "https://www.linkedin.com/in/max-menezes-447429328/",
    "location": "West Lafayette, IN",
    "university": "Purdue University",
    "degree": "Robotics Engineering Technology",
    "graduation": "May 2029",
    "headline_top": "Making ideas",
    "headline_bottom": "move.",
    "intro": "I'm Max, a Purdue student exploring the space where code meets the physical world. I build, simulate, and keep asking what comes next.",
    "about": "I'm drawn to engineering that moves beyond the screen. My work spans surgical-robotics simulation, local AI systems, and practical software for people and businesses.",
    "about_second": "From São Paulo to Purdue, I've followed the same curiosity: how can a well-built system make something work better? I like turning that question into something I can test.",
    "concentration": "Autonomy and UXVs · Signal Processing Option (planned)",
    "minor": "Electrical Engineering Technology (intended)",
    "gpa": "4.00",
    "honor": "Dean's List",
}

PROJECTS = [
    {
        "id": "surgical-robotics",
        "number": "01",
        "category": "Robotics / Research",
        "title": "A better position.\nA better possibility.",
        "short_title": "Surgical robotics",
        "description": "Exploring how robot-arm placement changes what's possible in robot-assisted surgery. A Python and PyBullet simulation evaluates base positions across three surgical scenarios.",
        "tags": ["Python", "PyBullet", "Inverse kinematics"],
        "date": "May — Sep 2026",
        "role": "Independent researcher",
        "base_poses": 81,
        "scenarios": 3,
        "details": [
            "Built a 3D simulation of a da Vinci Research Kit patient-side manipulator to evaluate 81 candidate base poses across three surgical scenarios.",
            "Ranked feasible configurations using inverse kinematics, collision and clearance checks, workspace coverage, manipulability, joint margin, and robustness metrics.",
            "Generated CSV/JSON results and figures for a manuscript submitted to LEPIC at Hospital das Clínicas, University of São Paulo Medical School, under Dr. Ricardo Zugaib Abdalla.",
        ],
        "note": "Simulation research; no clinical performance claims. The workspace graphic on this page is an illustration, not a plot of experimental results.",
    },
    {
        "id": "ai-os",
        "number": "02",
        "category": "Personal project / Automation",
        "title": "AI-OS",
        "short_title": "AI-OS",
        "description": "Exploring a personal assistant built around local models, Python, and everyday interfaces: WhatsApp, web, and voice.",
        "tags": ["Python", "Local models", "Automation"],
        "date": "2026",
        "role": "Personal project",
        "details": [
            "Developing a personal automation system with Python and Claude Code, with local models as the intended foundation.",
            "Exploring WhatsApp, web, and voice as interfaces for interacting with the assistant.",
            "The project brings together a hands-on interest in local AI, automation, and systems that fit into daily life.",
        ],
        "note": "An ongoing personal project. The diagram shows the intended system architecture.",
    },
    {
        "id": "modo-menezes",
        "number": "03",
        "category": "Entrepreneurship / Applied AI",
        "title": "Modo Menezes",
        "short_title": "Modo Menezes",
        "description": "Turning emerging tools into useful services for local businesses, from AI-built websites to chatbot and receptionist offerings.",
        "tags": ["Founder", "Web development", "Applied AI"],
        "date": "Aug 2026 — Present",
        "role": "Founder",
        "details": [
            "Founded Modo Menezes in August 2026 to offer practical AI services to local businesses.",
            "The service offering includes AI-built websites, chatbots, and AI receptionists.",
            "Delivered website work for Mr. Moustache Barbearia in São Paulo, shaping the service information, business story, and WhatsApp contact flow.",
        ],
        "note": "Focused on useful outcomes for small businesses.",
    },
    {
        "id": "bayer-platform",
        "number": "04",
        "category": "Industry project / Software",
        "title": "Learning, connected.",
        "short_title": "Bayer training platform",
        "description": "A digital training platform for Bayer Crop Science, built with an agile team to support technical learning and track performance.",
        "tags": ["JavaScript", "Full stack", "Agile"],
        "date": "Feb — Apr 2025",
        "role": "Full-stack developer · Team project",
        "details": [
            "Worked on a 10-week agile team building a technical training platform for Digital Technical Promoters supporting Climate FieldView.",
            "Developed user and administrator workflows to track individual and team performance.",
            "Built with Node.js, Express, EJS, Tailwind CSS, PostgreSQL, and Supabase.",
        ],
        "note": "Completed through project-based coursework at Inteli.",
    },
]

EXPERIENCE = [
    {"date": "Aug 2026 — Present", "organization": "Modo Menezes", "role": "Founder", "description": "Building practical AI and web services for local businesses.", "type": "Entrepreneurship"},
    {"date": "May — Sep 2026", "organization": "Surgical robotics research", "role": "Independent researcher", "description": "Simulation-based robot-arm placement research, mentored by Dr. Ricardo Zugaib Abdalla at LEPIC / HCFMUSP.", "type": "Research"},
    {"date": "Jul 2025", "organization": "C6 Bank", "role": "Finance intern · Profitability Division", "description": "Analyzed profitability and vehicle-finance data across 120 hours of project work. Developed a model to forecast Provision for Doubtful Debt growth.", "type": "Industry"},
    {"date": "Feb — Apr 2025", "organization": "Bayer Crop Science / Inteli", "role": "Full-stack developer · Team project", "description": "Developed a digital training platform in a 10-week agile team.", "type": "Project"},
]

SKILLS = {
    "Robotics & engineering": ["PyBullet", "Inverse kinematics", "3D simulation", "MATLAB", "AutoCAD"],
    "Code & systems": ["Python", "C", "JavaScript", "SQL", "Node.js", "HTML / CSS"],
    "Ways of working": ["Research", "Agile development", "Prototyping", "Data analysis"],
}
